# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd74a9c829834fff23b34b8eca2aa6e6965c35c33402d0a2e3af62929d9e3f64c1739199cc20ca4418de63f884c3e3cf92ab1fcdc70692b62bbec447de3e1fd0

test:
  secret_key_base: bd74a9c829834fff23b34b8eca2aa6e6965c35c33402d0a2e3af62929d9e3f64c1739199cc20ca4418de63f884c3e3cf92ab1fcdc70692b62bbec447de3e1fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
